[pytest]
<<<<<<< HEAD
norecursedirs =
    .git
    .venv
    venv
    __pycache__
    dataset
    instance
    pytest-cache-files-*
    .pytest_cache
=======
testpaths = tests

>>>>>>> 46a09c90cfcc0ec9f84d5761ca933d6cc76fa057
